- name: create dirs
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - /data/behavior-detection/
    - /data/fw-whitelist/
    - /data/blacklist-vulnerability/
    - /data/fw-whitelist
    - /data/fw-whitelist-custom
    - /data/rules
    - /data/firewall/ips/rules/netvine_engine/
    - /data/log/engines/dpi/
    - /data/configuration/southwest_engines
    - /usr/local/etc/southwest_engine/

- name: create file
  file: 
    path: "{{ item }}"
    state: touch
  with_items:
    - /usr/include/stropts.h

- name: install engine env
  yum: name={{ item }} state=present
  with_items:  # apt-cache madison nginx 查看可用版本
    - gcc
    - gcc-c++
    - gdb
    - pcre-devel
    - pcre
    - zlib-devel
    - ncurses-devel
    - readline-devel
    - mlocate
    - samba-devel
    - glib-devel
    - glib2-devel
    - thrift-devel
    - thrift-glib
    - thrift
    - compat-glibc-headers
    - libffi-devel
    - bzip2
    - openssl-libs
    - the_silver_searcher.x86_64
    - openssl
    - openssl-libs
    - openssl-devel
    - libpcap-devel
    - libnet-devel
    - libnfnetlink-devel
    - libnetfilter_queue-devel
    - gperftools-libs
    - jansson-devel
    - libcap-ng-devel
    - file-devel
    - libyaml-devel
    - sqlite-devel
    # - awk
    - bison
    - flex
    - mawk
    - dpkg
    - cscope
    - ctags

- name: copy libcapi
  copy: src=engine/libcapi.so dest=/usr/lib64 owner=root group=root

- name: copy libsharecfg
  copy: src=engine/libsharecfg.so dest=/usr/lib64 owner=root group=root

- name: copy config to /data 
  unarchive:
    src: engine/config.zip
    dest: /data/configuration/southwest_engines
    mode: '0755'

- name: copy threshold 
  copy:
    src: engine/threshold.config
    dest: /usr/local/etc/southwest_engine/
    mode: '0744'

- name: ldconfig
  shell: ldconfig