# 防火墙操作
- name: start firewalld.service
  service: 
    name: firewalld 
    state: started

# https://docs.ansible.com/ansible/latest/collections/ansible/posix/firewalld_module.html

- name: install firewall python module
  yum:
    name: python-firewall
    state: present

# 查看防火墙规则 firewall-cmd --state 运行状态
# firewall-cmd --zone=public --list-ports
- name: add port rule
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{item.port}}/{{item.proto}}"
    state: "{{item.state}}"
    zone: "{{item.zone}}"
  with_items:
    - {port: "443", proto: "tcp", state: "enabled", zone: "public" }     # https
    - {port: "22", proto: "tcp", state: "enabled", zone: "public" }    # ssh
    - {port: "1443", proto: "tcp", state: "enabled", zone: "public" }     # watcher
  vars:
    ansible_python_interpreter: /usr/bin/python

# 最后操作
- name: reboot system wait 5s
  reboot:
    post_reboot_delay: 5