- name: clean redis package
  shell: rm -fr  /tmp/{{ redis.package_name }}.tar.gz {{ redis.temp_dirs }}

- name: create redis config dirs
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/redis

- name: download redis
  shell: wget -O  /tmp/{{ redis.package_name }}.tar.gz {{ redis.package_url }}

- name: Decompress nginx
  shell: |
    mkdir {{ redis.temp_dirs }}
    tar xvf /tmp/{{ redis.package_name }}.tar.gz -C {{ redis.temp_dirs }}

- name: build redis
  shell:  make && make install PREFIX=/usr/local/redis 
  args:
    chdir: "{{ redis.temp_dirs }}/{{ redis.package_name }}"

- name: add redis cli
  lineinfile:
    path: ~/.bash_profile
    line: '{{ item }}'
    create: yes
  with_items:
    - 'export PATH="$PATH:/usr/local/redis/bin"'

# 要注意权限问题. redis:redis  
- name: cover redis conf
  copy: src=redis/redis.conf dest=/etc/redis/redis.conf owner=root group=root