# 自定义软件安装
- name: rm origin file
  shell: rm -fr "{{ soft.origin_path }}"

- name: rm old logs
  shell: rm -fr /data/logs

- name: create dirs
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - /data/logs/superv-engine
    - /data/logs/superv-redis
    - /data/logs/superv-server
    - /data/logs/superv-web
    - /data/logs/superv-watcher
    - /data/socket
    - "{{ soft.device_path }}"  # 最初版本
    - "{{ soft.origin_path }}"
    - /data/allow-list
    - /data/audit
    - /data/configuration
    - /data/coredump
    - /data/engine_conf 
    - /data/flowdata
    - /data/mysql
    - /data/network_attack
    - /data/redis
    - /data/report
    - /data/rules
    - /data/self-proto
    - /data/watcher

- name: copy key to device
  copy: 
    src: git/git_id_rsa 
    dest: "{{ soft.git_key_file }}"
    mode: '0400'
    owner: root
    group: root

- name: soft git clone code
  git:
    accept_hostkey: yes
    key_file: "{{ soft.git_key_file }}"
    repo: "{{ soft.soft_git_repo }}"
    dest: "{{ soft.soft_temp_path }}"
    version: "{{ soft.soft_git_branch }}"

- name: unzip soft package to dest
  shell: unzip -d "{{ soft.origin_path }}" "{{ soft.soft_temp_path }}/{{ soft.soft_package_file }}"

- name: create a link to origin soft
  shell: |
    rm -fr {{ soft.current_link_path }}
    ln -s "{{ soft.origin_path }}/" {{ soft.current_link_path }}

- name: 删除之前边车程序
  shell: rm -fr {{ soft.watcher_path }}

- name: wathcer git clone code
  git:
    accept_hostkey: yes
    key_file: "{{ soft.git_key_file }}"
    repo: "{{ soft.watcher_git_repo }}"
    dest: "{{ soft.watcher_path }}"
    version: "{{ soft.watcher_git_branch }}"

- name: rm git dir
  shell: |
    rm -fr  "{{ soft.origin_path }}/.git*"
    rm -fr  "{{ soft.watcher_path }}/.git*"

- name: modify dir permission
  shell: chmod +x "{{ soft.watcher_path }}/watcher"

- name: delete key from device
  shell: rm -fr "{{ soft.git_key_file }}"

- name: 拷贝device_info.conf 文件
  copy: src=soft/device_info.conf dest="{{ soft.device_path }}" owner=root group=root
