# supervisor 启动
# /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
- name: install supervisor
  yum: 
    name: supervisor 
    state: present

- name: stop and disable nginx
  service: 
    name: nginx 
    state: stopped
    enabled: false
  ignore_errors: true

- name: stop and disable redis
  service: 
    name: redis 
    state: stopped
    enabled: false
  ignore_errors: true

- name: stop and disable redis server
  service: 
    name: redis-server 
    state: stopped
    enabled: false
  ignore_errors: true

- name: clean conf
  shell: rm -fr /etc/supervisor/conf.d/*

- name: cover supervisor conf
  copy: src=supervisor/supervisord.conf dest=/etc/supervisord.conf owner=root group=root

- name: copy supervisor conf
  copy: src=supervisor/app/ dest=/etc/supervisor/conf.d/ owner=root group=root

- name: restart supervisor
  service: 
    name: supervisord
    state: restarted
    enabled: true

- name: restart redis
  supervisorctl:
    name: superv-redis
    state: restarted

- name: restart engine
  supervisorctl:
    name: superv-engine
    state: restarted

- name: restart server 
  supervisorctl:
    name: superv-server
    state: restarted

- name: restart nginx web
  supervisorctl:
    name: superv-web
    state: restarted