# 基础环境
- include: base.yml

# 自定义软件安装
- include: soft.yml

# 安装引擎运行环境
- include: engine.yml

# mysql 安装及配置
- include: mysql.yml

# nginx配置
- include: nginx.yml

# redis配置
- include: redis.yml

# supervisor配置
- include: supervisor.yml

# 最后的处理
- include: finally.yml