# 自定义软件安装
- name: rm origin file
  shell: rm -fr "{{ soft.build_script_path }}"

- name: create soft dirs
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ soft.build_path }}"

- name: soft git clone code
  git:
    accept_hostkey: yes
    key_file: "{{ soft.git_key_file }}"
    repo: "{{ soft.build_script_git_repo }}"
    dest: "{{ soft.build_script_path }}"
    version: "{{ soft.build_script_branch }}"

