# 安装nvm
# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
- name: copy nvm sh
  copy: src=nvm/nvm-install.sh dest=/tmp owner=root group=root

- name: install nvm1
  shell: bash -x /tmp/nvm-install.sh

- name: install nvm2 and node
  shell: /bin/bash -c "source ~/.nvm/nvm.sh && nvm install v14.21.2 && nvm alias default v14.21.2"

# - name: install cnpm
#   shell: npm install cnpm -g --registry=https://registry.npmmirror.com

- name: setup nvm .profile
  lineinfile:
    path: ~/.profile
    line: '{{ item }}'
    create: yes
  with_items:
    - 'export NVM_DIR="$HOME/.nvm"'
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm'
    
- name: nvm version
  shell: /bin/bash -c "source ~/.nvm/nvm.sh && nvm --version"
  register: nvm_version

- debug: msg="{{ nvm_version.stdout }}"

