- name: create dirs
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - /data/behavior-detection/
    - /data/fw-whitelist/
    - /data/blacklist-vulnerability/
    - /data/fw-whitelist
    - /data/fw-whitelist-custom
    - /data/rules
    - /data/firewall/ips/rules/netvine_engine/

- name: install engine env
  apt: name={{ item }} state=present
  with_items:
    - gcc
    - pkg-config
    - libpcre3
    - libpcre3-dev
    - libyaml-dev
    - libjansson-dev
    - libpcap-dev
    - rustc
    - cargo
    - libcap-ng-dev
    - libnspr4-dev
    - libnss3-dev
    - libmagic-dev
    - liblz4-dev
    - make
    - zlib1g
    - zlib1g-dev
    - libnet1-dev
    - libnetfilter-queue-dev
    - libnetfilter-queue1
    - libhyperscan-dev
    - automake
    - libreadline-dev
    - libncurses-dev

- name: install debug env
  apt: name={{ item }} state=present
  with_items:
    - linux-tools-common
    - linux-tools-generic
    - linux-cloud-tools-generic

- name: copy deb
  copy: src=engine/ld_netvine_fw.conf dest=/etc/ld.so.conf.d/ owner=root group=root

- name: ldconfig
  shell: ldconfig