# 自定义软件安装
- name: rm origin file
  shell: rm -fr "{{ soft.origin_path }}"

- name: rm old logs
  shell: rm -fr /data/logs

- name: create dirs
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - /data/logs/superv-engine
    - /data/logs/superv-redis
    - /data/logs/superv-server
    - /data/logs/superv-web
    - /data/logs/superv-watcher
    - /data/logs/fw-engine
    - /data/socket
    - "{{ soft.device_path }}"  # 最初版本
    - "{{ soft.origin_path }}"
    - /data/logs/fw-nft

- name: copy key to device
  copy: 
    src: git/git_id_rsa 
    dest: "{{ soft.git_key_file }}"
    mode: '0400'
    owner: root
    group: root

- name: soft git clone code
  git:
    accept_hostkey: yes
    key_file: "{{ soft.git_key_file }}"
    repo: "{{ soft.soft_git_repo }}"
    dest: "{{ soft.soft_temp_path }}"
    version: "{{ soft.soft_git_branch }}"

- name: unzip soft package to dest
  shell: unzip -d "{{ soft.origin_path }}" "{{ soft.soft_temp_path }}/{{ soft.soft_package_file }}"

- name: create a link to origin soft
  shell: |
    rm -fr {{ soft.current_link_path }}
    ln -s "{{ soft.origin_path }}/" {{ soft.current_link_path }}

- name: 删除之前边车程序
  shell: rm -fr {{ soft.watcher_path }}

- name: wathcer git clone code
  git:
    accept_hostkey: yes
    key_file: "{{ soft.git_key_file }}"
    repo: "{{ soft.watcher_git_repo }}"
    dest: "{{ soft.watcher_path }}"
    version: "{{ soft.watcher_git_branch }}"

- name: rm git dir
  shell: |
    rm -fr  "{{ soft.origin_path }}/.git*"
    rm -fr  "{{ soft.watcher_path }}/.git*"

- name: modify dir permission
  shell: chmod +x "{{ soft.watcher_path }}/watcher"

- name: delete key from device
  shell: rm -fr "{{ soft.git_key_file }}"

- name: 拷贝device_info.conf 文件
  copy: src=soft/device_info.conf dest="{{ soft.device_path }}" owner=root group=root

# 日志管理
- name: change owner and mode
  shell: |
    chown root:syslog /data/logs/fw-nft
    chmod g+w /data/logs/fw-nft
    touch /data/logs/fw-nft/nft.log
    chown syslog:adm /data/logs/fw-nft/nft.log
    chmod 640 /data/logs/fw-nft/nft.log

- name: config rsyslog
  copy:
    src=log/19-nft.conf dest=/etc/rsyslog.d/ owner=root group=root

- name: config logrotate
  copy:
    src=log/nft dest=/etc/logrotate.d/ owner=root group=root

- name: Ensure a job that runs every 5 minute. Create an entry like "*/5 * * * * /bin/bash /opt/firewall/ips/bin/logrotate-nft.sh"
  ansible.builtin.cron:
    name: "logrotate-nft"
    minute: "*/5"
    job: "/bin/bash /opt/firewall/ips/bin/logrotate-nft.sh >/dev/null 2>&1"

- name: restart rsyslog and cron
  service: name={{ item }} state=restarted
  with_items:
    - rsyslog
    - cron
