# 运行指令
# ansible-playbook code/ansible/main.yml -i /etc/ansible/hosts -vv
- name: prepare env
  shell: |
    apt-mark hold linux-image-`uname -r`
    apt-mark hold linux-headers-`uname -r`
    apt-mark hold linux-modules-extra-`uname -r`
    apt autoremove --purge snapd -y
    apt autoremove --purge cloud-init -y
  ignore_errors: true

- name: apt update
  shell: apt update
  ignore_errors: true

- name: remove old soft 
  shell: |
    apt-get purge --auto-remove redis -y

- name: common env
  apt: name={{ item }} state=present
  with_items:  # apt-cache madison nginx 查看可用版本
    - supervisor
    - nginx=1.18.0-0ubuntu1.4 
    - redis=5:5.0.7-2
    - bridge-utils
    - nftables=0.9.3-2
    - gdb
    - net-tools
    - tcpreplay
    - unzip
    - ntp
    - ntpdate
    - cpufrequtils
    - libnftables-dev=0.9.3-2
    - lm-sensors

# timedatectl 可以查看当前时区, 查看时间 Z=Asia/Shanghai date
- name: Set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai

- name: 同步时间 ntp.ntsc.ac.cn
  shell: ntpdate -u ntp.ntsc.ac.cn
  ignore_errors: true

- name: 打开路由转发功能  
  copy: src=sysctl.conf dest=/etc/sysctl.conf owner=root group=root