# 自定义软件安装
- name: rm origin file
  shell: rm -fr "{{ soft.origin_path }}"

- name: create dirs
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/firewall         # 当前版本  
    - /opt/origin/firewall   # 最初版本
    - /data/logs/superv-engine
    - /data/logs/superv-redis
    - /data/logs/superv-server
    - /data/logs/superv-web
    - /data/logs/superv-watcher
    - /data/logs/fw-engine
    - /data/socket
    - "{{ soft.origin_path }}"
    - "{{ soft.watcher_path }}"
    - "{{ soft.device_path }}"
    - /data/logs/fw-nft

- name: unzip soft package 
  unarchive:
    src: soft/firewall_update.zip
    dest: "{{ soft.origin_path }}"  
    mode: 0755

- name: create a link to /opt/firewall/ 
  shell: |
    rm -fr /opt/firewall
    ln -s "{{ soft.origin_path }}/" /opt/firewall

- name: 删除之前边车程序
  shell: rm -fr {{ soft.watcher_path }}

- name: 拷贝sidecar升级包到/tmp
  unarchive:
    src: soft/watcher-product-firewall.zip
    dest: /tmp
    mode: 0755

- name: 升级sidecar到{{ soft.watcher_path }}
  shell: mv /tmp/watcher-product-firewall {{ soft.watcher_path }}

- name: 拷贝device_info.conf 文件
  copy: src=soft/device_info.conf dest="{{ soft.device_path }}" owner=root group=root

# 日志管理
- name: change owner and mode
  shell: |
    chown root:syslog /data/logs/fw-nft
    chmod g+w /data/logs/fw-nft
    touch /data/logs/fw-nft/nft.log
    chown syslog:adm /data/logs/fw-nft/nft.log
    chmod 640 /data/logs/fw-nft/nft.log

- name: config rsyslog
  copy:
    src=log/19-nft.conf dest=/etc/rsyslog.d/ owner=root group=root

- name: config logrotate
  copy:
    src=log/nft dest=/etc/logrotate.d/ owner=root group=root

- name: Ensure a job that runs every 5 minute. Create an entry like "*/5 * * * * /bin/bash /opt/firewall/ips/bin/logrotate-nft.sh"
  ansible.builtin.cron:
    name: "logrotate-nft"
    minute: "*/5"
    job: "/bin/bash /opt/firewall/ips/bin/logrotate-nft.sh >/dev/null 2>&1"

- name: restart rsyslog and cron
  service: name={{ item }} state=restarted
  with_items:
    - rsyslog
    - cron
