- name: remove current mysql
  shell: apt autoremove mysql-* -y

# get_url下载403，使用离线文件 
# dpkg-deb -c mysql-apt-config_0.8.6-1_all.deb 

# ./usr/share/doc/mysql-apt-config/
# ./usr/share/doc/mysql-apt-config/changelog.Debian.gz 
- name: install depend
  apt: name={{ item }} state=present
  with_items: 
    - python3-pip
    - libtinfo5
    - libmecab2

- name: pymysql
  shell: pip3 install pymysql

- name: check mysqld bin file
  stat:
    path: /usr/sbin/mysqld
  register: mysqld_file

- name: download mysql package
  shell: wget -O  /tmp/{{ mysql.mysql_package }} {{ mysql.mysql_package_url }}

- name: Decompress
  shell: |
    mkdir {{ mysql.mysql_tmp_dirs }}
    tar xvf /tmp/{{ mysql.mysql_package }} -C {{ mysql.mysql_tmp_dirs }}
    cd {{ mysql.mysql_tmp_dirs }}

- name: delete test package
  shell: rm -fr *test*.deb
  args:
    chdir: "{{ mysql.mysql_tmp_dirs }}"

- name: install mysql
  shell: dpkg -i *.deb 
  args:
    chdir: "{{ mysql.mysql_tmp_dirs }}"
  environment:
        DEBIAN_FRONTEND: noninteractive
  when: mysqld_file.stat.exists == false

- name: timed wait 5s
  pause: seconds=5

